name: pay_sphere_app
description: "Application de gestion bancaire"
publish_to: 'none'
version: 1.0.0+1


environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.1
  flutter_secure_storage: ^9.0.1
  shared_preferences: ^2.2.3
  go_router: 15.1.2
  intl: ^0.20.2
  url_launcher: ^6.3.1
  share_plus: ^11.0.0
  path_provider: ^2.1.2
  pdf: ^3.10.4
  flutter_local_notifications: ^19.2.1
  permission_handler: ^12.0.0+1
  image_picker: ^1.1.2
  image_cropper: ^9.1.0
  flutter_launcher_icons: ^0.14.3
  provider: ^6.1.5
  flutter_dotenv: ^5.2.1




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - lib/assets/images/first.jpg
    - lib/assets/images/WERO_logo.png
    - lib/assets/avatar/00.jpg
    - lib/assets/avatar/01.jpg
    - lib/assets/avatar/02.jpg
    - lib/assets/avatar/10.jpg
    - lib/assets/avatar/11.jpg
    - lib/assets/avatar/12.jpg
    - lib/assets/avatar/20.jpg
    - lib/assets/avatar/21.jpg
    - lib/assets/avatar/22.jpg
    - lib/assets/avatar/30.jpg
    - lib/assets/avatar/31.jpg
    - lib/assets/avatar/32.jpg
    - lib/assets/avatar/40.jpg
    - lib/assets/avatar/41.jpg
    - lib/assets/avatar/42.jpg
    - lib/assets/avatar/50.jpg
    - lib/assets/avatar/51.jpg
    - lib/assets/avatar/52.jpg
    - lib/assets/avatar/60.jpg
    - lib/assets/avatar/61.jpg
    - lib/assets/avatar/62.jpg


flutter_icons:
  android: true
  image_path: "lib/assets/icon/icone.png"
  adaptive_icon_background: "#0086db"
  adaptive_icon_foreground: "lib/assets/icon/icone.png"










